# Generated by Django 4.2.2 on 2023-07-05 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweeter', '0006_profile_instagram_link_profile_facebook_link_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='homepage_link',
            new_name='Website_link',
        ),
    ]
