# Generated by Django 4.2.2 on 2023-07-31 18:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tweeter', '0009_profile_tweets'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('profile_bio', models.TextField(blank=True, max_length=250, null=True)),
                ('website_link', models.CharField(blank=True, max_length=250, null=True)),
                ('facebook_link', models.CharField(blank=True, max_length=250, null=True)),
                ('instagram_link', models.CharField(blank=True, max_length=250, null=True)),
                ('linkedin_link', models.CharField(blank=True, max_length=250, null=True)),
                ('birthdate', models.DateField(default='2000-01-01', verbose_name='Birthdate')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is_Active')),
                ('is_staff', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('follows', models.ManyToManyField(blank=True, related_name='followed_by', to='tweeter.adminprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('profile_bio', models.TextField(blank=True, max_length=250, null=True)),
                ('website_link', models.CharField(blank=True, max_length=250, null=True)),
                ('facebook_link', models.CharField(blank=True, max_length=250, null=True)),
                ('instagram_link', models.CharField(blank=True, max_length=250, null=True)),
                ('linkedin_link', models.CharField(blank=True, max_length=250, null=True)),
                ('birthdate', models.DateField(default='2000-01-01', verbose_name='Birthdate')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is_Active')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('follows', models.ManyToManyField(blank=True, related_name='followed_by', to='tweeter.userprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='hashtag',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='hashtag',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='follows',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='tweets',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='AccountRecycle',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='description',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='hashtags',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='media',
        ),
        migrations.AddField(
            model_name='comment',
            name='likes',
            field=models.ManyToManyField(related_name='liked_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tweet',
            name='text',
            field=models.CharField(default='', max_length=280),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AccountRecycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Hashtag',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tweets',
            field=models.ManyToManyField(related_name='user_profiles_tweets', to='tweeter.tweet'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='tweets',
            field=models.ManyToManyField(related_name='admin_profiles_tweets', to='tweeter.tweet'),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accountrecycle',
            name='user_account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tweeter.userprofile'),
        ),
    ]
