# Generated by Django 4.2.2 on 2023-07-31 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweeter', '0010_adminprofile_userprofile_remove_hashtag_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountrecycle',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
