# Generated by Django 4.2.2 on 2023-08-01 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweeter', '0013_tweeterprofile'),
    ]

    operations = [
    ]
