# Generated by Django 4.2.2 on 2023-08-01 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweeter', '0014_auto_20230801_0920'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TweeterProfile',
        ),
    ]
